import type { Metadata } from "next";
import "./globals.css";
import TopBar from "./components/topbar";
import Navigation from "./components/navigation";

export const metadata: Metadata = {
  title: "TrampooFy - Reports para ser Promovido",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <TopBar />
        <div className="flex flex-col justify-center items-center h-screen">
          {children}
        </div>
        <Navigation />
      </body>
    </html>
  );
}
